from functions.get_file_content import get_file_content

print("START TEST ================================================")
print(get_file_content("calculator", "lorem.txt"))
print("===========================================================")
print(get_file_content("calculator", "main.py"))
print("===========================================================")
print(get_file_content("calculator", "pkg/calculator.py"))
print("===========================================================")
print(get_file_content("calculator", "/bin/cat"))
print("===========================================================")
print(get_file_content("calculator", "pkg/does_not_exist.py"))
print("===========================================================")
print(get_file_content(".", "functions"))
print("===========================================================")
print(get_file_content(".", "../bookbot/README.md"))
print("END TEST===================================================")